### ISSUE TITLE
Usercase

### ISSUE THREAD

**Issue by hoangsep** [davidsainty/optiboot#1]
Hi. 

Could you please explain a bit more about how to use xbeeboot? Ideally will be like having a usercase. I am a beginner with bootloader. Normally I just load code using the Arduino IDE so I don't know how to use xbeeboot. How do I connect the xbee in the computer side? How do I upload the code? How do I add the "xbee programmer" option to the IDE?

Regards,

**Comment by davidsainty** [comment]
Hi,

The XBee on the computer side is connected via the serial port.  This is very standard, I didn't think of documenting that :)  I use an XBee USB Explorer: https://nicegear.co.nz/wireless/sparkfun-xbee-explorer-usb/

The bootloader upload can be done via any ISP programmer.  I use ArduinoISP, which is very easy to set up if you have two Arduinos to work with: https://www.arduino.cc/en/Tutorial/ArduinoISP

The avrdude patch requires rebuilding avrdude with the patch applied.  This is probably too big a topic to cover here.  I'm hoping that a later release of avrdude will include the support natively.  But if you google "patch files" and get avrdude building working you'll be on the way,,,

Regarding the IDE: I tend to use the build tools directly, so I normally ignore the IDE.  However, if you solve everything else I promise I'll figure out how to configure the IDE bootloader :)

**Comment by hoangsep** [comment]
Hi. 

I recompiled the avrdude but still cannot do OTA. The avrdude always reported that the remote xbee is not responding after sending the AT command D6. So I go and took a look at the source code.At line 544 of xbee.c, the sendAPIRequest function is called as: 
sendAPIRequest(fd, 0x17, sequence,
                 -1, -1, -1,
                 0x02, -1, length, buf);
However, at line 107 of xbee.c, the sendAPIRequest is defined as 
static void sendAPIRequest(union filedescriptor \* const fd,
                           const unsigned char apiType,
                           const int apiOption,
                           const int prePayload1,
                           const int prePayload2,
                           const int packetType,
                           const int sequence,
                           const int appType,
                           const unsigned int dataLength,
                           const unsigned char \* const data)
It looks like the order of the parameters doesn't fit. Could you please check on that?

Regards,

**Comment by hoangsep** [comment]
Btw, which version of avrdude are you using?

Regards,

**Comment by davidsainty** [comment]
The patch is against 6.1, and that's what it's tested against.  There is a recent 6.2 release of avrdude, but it looks like it has a serious baud rate setting bug.  However, the patch will probably apply cleanly to pretty much any version.

**Comment by davidsainty** [comment]
The sendAPIRequest() call somewhat evolved, and I can see why that looks confusing!  Possibly the arguments should just be arg1..arg6, rather than names.  But I'm pretty sure the API message is correct.

You can try multiple -v options to get debugging information.

If the remote XBee is not responding ("D6" is the first remote command) it may well be a real ZigBee networking problem, and they really can't talk to each other.  How are your XBee's currently set up?  Can they normally talk to each other ok?

**Comment by hoangsep** [comment]
Hi. I realized that the program get stuck in the loop in xbeedev_send() due to no ACK received from the mcu. Then when I check the mcu, it isn't in the bootloader mode. It is still running the program that I loaded before that. The reset command (D3) worked fine and the mcu seemed to be reset, so I wonder whether the timeout is too short and the mcu go back to normal mode? I am using ATmega328p at 8MHz without crystal.

**Comment by davidsainty** [comment]
I wonder if the lack of crystal might be the issue - serial IO is quite demanding on clock precision.  Any chance you can throw in a crystal?

I take it you're getting past the D6 AT command now.  The Optiboot-style reset timeout is pretty short (and hardware limited, unfortunately), but unless your ZigBee network is struggling the timeout shouldn't be the problem - but it's certainly a symptom of whatever the problem is...

**Comment by hoangsep** [comment]
Hi. I am getting an Uno board to try with the crystal. In the mean time, is there anything I can do? What is the default timeout? What is the maximum that I can set? Where is it set in the bootloader code?

**Comment by davidsainty** [comment]
Search for WATCHDOG_8S in xbeeboot.c.  Unfortunately, because it uses the watchdog, it can't be set any longer than 8 seconds (according to the data sheet).

You could set it to WATCHDOG_OFF - but then it will be hard to get the application to start, because the watchdog kicks off the application.  That might be a useful test, but not a very useful solution :)

You definitely have API-mode firmware in the remote XBee I assume?

**Comment by davidsainty** [comment]
Oh, BTW, have you had the 328P talking to the XBee successfully previously?  If you have then presumably the internal clock is precise enough.  I've never tried using the internal clock, I always assumed it'd be too imprecise for serial IO - but I don't recall ever actually doing the maths to be sure...

**Comment by hoangsep** [comment]
Hi. Yes, I have the 328p talking to XBee successfully without crystal for a few months alr. So the default timeout is 8s? If it is, then something is wrong, because from what I see, the application run almost immediately after the second D3 command.

**Comment by davidsainty** [comment]
Can you attach an avrdude log?  Just in case I can spot any clues...

With avrdude -v -v -v -v

**Comment by hoangsep** [comment]
Hi. Unfortunately the setup is not with me right now. I will send you the after 3 hours.

**Comment by hoangsep** [comment]
Attached is the log file. I compressed it to .zip as Github does not allow .log file. In the log file, there are also a few comments added by me for debugging.
[avrdude.log.zip](https://github.com/davidsainty/xbeeboot/files/56674/avrdude.log.zip)

**Comment by davidsainty** [comment]
It doesn't seem like there's any response at all after the reset.  The XBee's seem to talk ok, and I take it from your comments that it appears your 328P program does restart - telling us the reset circuitry is behaving.

Anything about the serial that might be off?  Is XBee set to all defaults?  9600bps?  Any hardware flow control in use?  Has your 328P application proven that both serial send and serial receive are working ok?

Are you able to connect the 328P directly to a serial port (or Arduino?). You could verify that the bootloader is basically working by doing an avrdude -c xbee directly to the serial port with no ZigBee address.  It handles that as a special case, which will at least show that the xbeeboot bootloader is functional.  If the clock is 16MHz you'll need to use 19200 baud, if the clock is 8MHz you'll need to use 9600 baud.

**Comment by hoangsep** [comment]
Hi. My 328p has been able to both send and receive data through xbee at 9600bps for a while now so I don't think that is the problem. About the baud rate, I saw this in the xbeeboot.c:

/\* set the UART baud rate defaults */
#ifndef BAUD_RATE
#if F_CPU >= 8000000L
#define BAUD_RATE   115200L // Highest rate Avrdude win32 will support
#elif F_CPU >= 1000000L
#define BAUD_RATE   9600L   // 19200 also supported, but with significant error
#elif F_CPU >= 128000L
#define BAUD_RATE   4800L   // Good for 128kHz internal RC
#else
#define BAUD_RATE 1200L     // Good even at 32768Hz
#endif
#endif

does that mean the baud rate is 115200 at 8MHz? 
I will try connecting m328p directly and post the result here asap.

**Comment by davidsainty** [comment]
It should be 9600 for 8MHz.  Your direct connection will verify that either way...

Direct parameter syntax is: avrdude -c xbee -P @/dev/ttyACM0 

I.e. still have the "@" but with no remote address.

**Comment by davidsainty** [comment]
BTW: What's your arrangement of coordinator, routers and endpoints?

**Comment by hoangsep** [comment]
The XBee connected to the 328p is an end device with cyclic sleep. The Xbee connected to the computer is the coordinator. Both are in API 2.

**Comment by hoangsep** [comment]
btw, how do I connect the reset wire in direct mode?

**Comment by davidsainty** [comment]
Same as an Arduino (which is exactly how I have tested in the past).  From memory it's the DTR line, but I'm not sure whether a direct connection is fine or whether it needs to be inverted.  I suspect direct connection...

**Comment by hoangsep** [comment]
pi@raspberrypi ~ $ sudo avrdude -vv  -c xbee -P @/dev/ttyACM0 -p m328p -U "flash:w:Blink.ino.hex"

avrdude: Version 6.1, compiled on Dec  1 2015 at 17:47:22
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

```
     System wide configuration file is "/usr/local/etc/avrdude.conf"
     User configuration file is "/root/.avrduderc"
     User configuration file does not exist or is not a regular file, skipping

     Using Port                    : @/dev/ttyACM0
     Using Programmer              : xbee
```

avrdude: Baud 19200
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724671.951305 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724672.952788 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724673.954151 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724674.955511 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724675.956970 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724676.958448 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724677.959903 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724678.961318 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724679.962753 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding

**Comment by davidsainty** [comment]
Direct mode defaults to 19200baud.  You may need -b 9600 ?

**Comment by davidsainty** [comment]
If your clock is 8MHz use avrdude -b 9600
If your clock is 16MHz use avrdude -b 19200

**Comment by hoangsep** [comment]
sudo avrdude -vv  -c xbee -b 9600  -P @/dev/ttyACM0 -p m328p -U "flash:w:Blink.ino.hex"

avrdude: Version 6.1, compiled on Dec  1 2015 at 17:47:22
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

```
     System wide configuration file is "/usr/local/etc/avrdude.conf"
     User configuration file is "/root/.avrduderc"
     User configuration file does not exist or is not a regular file, skipping

     Using Port                    : @/dev/ttyACM0
     Using Programmer              : xbee
     Overriding Baud Rate          : 9600
```

avrdude: Baud 9600
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724964.614131 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724965.615494 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724966.616811 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724967.618210 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724968.619545 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724969.620877 1, 1, 23, 48
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1449724970.622204 1, 1, 23, 48

**Comment by davidsainty** [comment]
Oh, from an RPi, very nice :)

What happens with: sudo avrdude -vv -c arduino -b 9600 -P /dev/ttyACM0 -p m328p -U "flash:w:Blink.ino.hex"

**Comment by hoangsep** [comment]
It is not working. It looks like my uno board is having problem. I haven't used it for a long time. I have always used the USBtiny programmer. 

sudo avrdude -vv -c arduino -b 9600 -P /dev/ttyACM0 -p m328p -U "flash:w:Blink.ino.hex"

avrdude: Version 6.1, compiled on Dec  1 2015 at 17:47:22
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

```
     System wide configuration file is "/usr/local/etc/avrdude.conf"
     User configuration file is "/root/.avrduderc"
     User configuration file does not exist or is not a regular file, skipping

     Using Port                    : /dev/ttyACM0
     Using Programmer              : arduino
     Overriding Baud Rate          : 9600
```

avrdude: ser_recv(): programmer is not responding
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: ser_recv(): programmer is not responding
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
avrdude: ser_recv(): programmer is not responding
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x00
avrdude: ser_recv(): programmer is not responding
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x00
avrdude: ser_recv(): programmer is not responding
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x00

**Comment by davidsainty** [comment]
It might be the baud rate.  Try every baud rate from 4800, 9600, 19200 ... up to 115200 with -c arduino,  I'd be surprised if it never jumps into action at any of those...

**Comment by hoangsep** [comment]
I tried 4800, 9600, 14400, 19200, 28800, 38400, 57600, 115200 but none of them works

**Comment by davidsainty** [comment]
Well this is all very frustrating...  Can you tell if it's resetting?

**Comment by hoangsep** [comment]
Actually I am ssh-ing to the pi from outside, so I can't see. Maybe I tried to solve the Uno problem first after I get home then I will get back to you.

**Comment by davidsainty** [comment]
Ok, sounds like an approach.

**Comment by hoangsep** [comment]
Hi. It took me a while. So now:
- My Uno runs normally with Optiboot
- I can burn bootloader and load code using xbeeboot with USBtiny
- I can not upload code using xbeeboot with arduino as programmer. The mcu doesn't seem to reset either.

I am trying to recompile the xbeeboot hex file but I am having some problem with that. In the mean time could you please double check the hex file in the repo?

Regards,

**Comment by davidsainty** [comment]
It looks like the hex file is correct...  Maybe the 328P flags are wrong during bootloader programming, they are slightly different for xbeeboot from the optiboot settings because xbeeboot is 1kB.

gmake atmega328_pro8_isp

avrdude  -c stk500v1 \
              -p atmega328p -P /dev/ttyACM0 -b9600 \
-e -u -U lock:w:0x3f:m -U efuse:w:0x05:m -U hfuse:w:0xDC:m -U lfuse:w:0xFF:m \
-U flash:w:xbeeboot_atmega328_pro_8MHz.hex -U lock:w:0x2f:m

**Comment by hoangsep** [comment]
I recompiled the xbeeboot hex file, burned it into the uno using usbtiny, but still cannot upload code using arduino programmer.

**Comment by davidsainty** [comment]
Did you end up with the same hex file?  It's a pretty tight squeeze byte-wise, different compilers might potentially blow the bootloader code limit.  Of course, that's unlikely to be our problem as the original hex file also doesn't work...

What command is used to burn the bootloader?  In particular, make sure the hfuse setting is correct (0xDC).

**Comment by hoangsep** [comment]
Yes the hfuse setting is correct. It is so confuse right now, considering that optiboot works.

**Comment by davidsainty** [comment]
Which of the optiboot hex files are you using that works?

**Comment by hoangsep** [comment]
The one that comes with arduino 1.6.6

**Comment by davidsainty** [comment]
optiboot_atmega328.hex?  And you're also using xbeeboot_atmega328.hex?

**Comment by hoangsep** [comment]
Yes. With xbeeboot I also tried the xbeeboot_atmega328_pro_8MHz.hex although I think there is no difference.

**Comment by davidsainty** [comment]
There's a baud rate difference too.  Default for xbeeboot is 9600 (assuming CPU clock speed is matched).  Default for optiboot is 115200 I think.  So you need something like -b 9600 -c arduino to talk to xbeeboot, and just -c arduino for optiboot.  Does that help?

**Comment by hoangsep** [comment]
Whoa, suddenly I can upload code using arduino programmer at baudrate 19200.

**Comment by hoangsep** [comment]
Finally I can OTA with my Uno, with crystal at baudrate 19200. Now I think I need to edit the fuse for it to run properly at 9600 and without crystal. 
BTW, the fuse settings in the board-1.6.txt in the repo and the fuse settings that you posted here are different.

**Comment by davidsainty** [comment]
I take it the crystal is 16MHz and the Bootloader is the 8MHz hex file. So
that chip, in theory, will work with an 8MHz clock and 9600baud XBee.

You actually did a real OTA successfully with the XBee set to 19200baud, is
that correct? Or did you simulate it with a direct connection?

**Comment by hoangsep** [comment]
The crystal is 16MHz and yes, it is a real OTA with XBee at 19200.

**Comment by davidsainty** [comment]
Great :)  I'm really interested to hear how it goes now with the chip's
internal clock. Sounds like it's ready to go...

**Comment by hoangsep** [comment]
Hi. 

I think I know why. My power supply is 3.3V only but I didn't calibrate the internal RC so the UART baudrate is not totally correct. Normally I send and receive too many data so sometimes some data is missing I also doesn't notice. 

Now I can OTA with 5V supply and internal RC 8MHz (low fuse = 0xE2). 

Because I use direct battery power so my voltage is going to change with time as the battery run out, I think I will just add a 8MHz crystal to the next PCB spin and set low fuse to 0xFF. I think I will need to do a few more testing about this. Hope it work :))

In the end, I think the problem is really the baudrate, just as you suspected from the start. Thank you very much for your support and timely response. I really appreciate this. 

Regards,

**Comment by ghost** [comment]
Just for reference for anyone who wants to know, I gave up on trying to figure out how to get this to work with the Arduino IDE.

I was able to get this to work though using avrdude.
Enviroment: Windows, Avrdude, custom atmega328p 8MHz board.

Here is the command to program to burn the bootloader:
avrdude -c usbtiny -p m328p -b9600 -e -u -U lock:w:0x3f:m -U efuse:w:0xFD:m -U hfuse:w:0xDC:m -U lfuse:w:0xFF:m -U flash:w:xbeeboot_atmega328_pro_8MHz.hex -U lock:w:0x2f:m

Here was the command to upload my sketch hex file:
avrdude -b9600 -c arduino -p m328p -P COM23 -v m328p -D -U flash:w:slow.hex

Something to note, you cannot have USB programming and xBee connected at the same time to do local updates. It didnt work for me. OTA with FTDI plugged in still worked though. Maybe I will add a double throw switch when I want to program it.
