### ISSUE TITLE
Questions regarding a different path to XBee OTA firmware uploads

### ISSUE THREAD

**Issue by TGit-Tech** [davidsainty/optiboot#12]
Hi David,

This isn't an issue - but I just wanted to ask a few questions about this implementation to see if I've investigated this subject thoroughly and correctly and get your opinion on a new path as described in #3.  I would've dropped an email but I couldn't find one.

1) You stated in the Readme that this boot-loader uploads via USB but needed to occur at 9600 baud rate.

Can you concur that I've investigated this subject correctly?  Its my understanding that the original "factory" boot-loader communicates serially at 115200?  As other posts I have read are using high-data capable devices to do remote firmware uploads.

2) Is there any chance you can quickly describe the bootloader's functionality and abilities.

Most importantly what exactly triggers the difference between, say the "Serial Monitor" transferring debug messages and uploading firmware via USB Serial?  I've been guessing that perhaps serial data introduced at the beginning of a reset is automatically taken for granite as firmware code, stored and launched - otherwise if the Serial connection is dead proceeds to run the sketch.

3) While investigating remote firmware uploading and solutions that brilliant people like yourself have come up with; I had wondered/considered if it was possible to use the XBee's remote firmware ( General Purpose Flash ) memory in the same sense.

As described here in the digi docs
https://www.digi.com/resources/documentation/Digidocs/90002126/reference/r_about_gpm.htm?TocPath=Advanced%20application%20features%7CGeneral%20Purpose%20Flash%20Memory%7C_____0

Which even states that host firmware upload storage could be one of its functions/uses.

I just wanted to check if you'd investigated this approach at all - if there were hang ups or how exactly one might go about accomplishing this ( perhaps without a specific bootloader re-programmed ).

Any thoughts, suggestions or comments would be greatly appreciated.

**Comment by davidsainty** [comment]
Hi, I'll answer these one at a time :)

1. The boot loader needs to be compiled for a specific baud rate.  The default XBee serial rate is 9600, so just for convenience I standardised on that because it's easier to get going with the XBee devices.  There really isn't any reason that a faster rate can't be used otherwise.

That's the primary reason I went with 9600.  The other reason I didn't really consider increasing the default baud rate is that the 9600bps serial isn't really the limiting factor in a ZigBee mesh. At least, it doesn't appear that way to me.

**Comment by davidsainty** [comment]
2. The boot loader runs immediately after a hard reset, and switches to running application code after a short delay.  The received data needs to conform to either the standard Arduino boot loader protocol, or XBee API packets that encapsulate a simple protocol that in turn encapsulates the Arduino boot loader protocol.

So yes, the reset is crucial, and is triggered out-of-band by toggling a GPIO pin off the XBee.  The following serial data needs to follow a fairly drawn-out protocol to execute the code loading process though, which is even less likely to happen by chance than with the standard Arduino boot loader.

**Comment by davidsainty** [comment]
3. There are XBees that support application code, but I haven't tried using them.  I would tend to expect that if the XBee supports an application, it might well be worth trying to put your entire program on that and avoid an Arduino/Atmel chip at all.  If you are deciding to go the Atmel chip route, then having an XBee capable boot loader is probably not a negative thing, and you can use the cheaper XBees.

I guess your motivation is a desire to work around the need to replace the boot loader on the Atmel.  My experience is that that's only daunting before you do it, and probably not the really challenging part of your project if you're doing anything wireless embedded :)

**Comment by TGit-Tech** [comment]
Thank You so Much for those detailed answers!  They are so very helpful and my understanding has been expanded 10-fold :)

#3 fixed my thinking on this path;  I was about to explain how my XBee modules didn't have programmable micro-controllers.

But after re-visitng the document linked above about "General Flash" the words "XBee 868LP RF Modules provide" finally came to my attention.  Somehow I automatically skipped that on first reading it since the document was part of the S3B DigiMesh Kit learning guide.

Embarrassing mistake :) - still thank you so much for epanding on those topics of which none of which I'd found earlier.

**Comment by davidsainty** [comment]
You're welcome :)
