### ISSUE TITLE
Pretty Lost

### ISSUE THREAD

**Issue by ghost** [davidsainty/optiboot#4]
Hi everyone. I am trying to get this working and this is where I have gotten so far.
(I am on a windows PC)

-I updated the Arduino Uno bootloader with the new xBeeBoot bootloader. 
-Downloaded the latest avrdude 5.11
-Downloaded the xBee Patch for avrdude
-Setup both xBee S2C in API mode and verified connection.
-Exported a test program from Arduino as a hex (w/bootloader) ? 

What I am stuck on:
-I cant seem to find a way to "patch" the xbee patch file to avrdude, wouldn't it be easier if you sourced a link to patched versions of avrdude in linux/windows?

-Once patched, what is the command to send the hex file to the remote xBee MAC ? 

Thanks!

**Comment by davidsainty** [comment]
If you do have access to a Linux box, the "patch" command can be used to apply the patch.  I'm honestly not sure if avrdude even runs on Windows, but if it does I think probably the patch would work...

I encourage you to vote for the avrdude patch, so it gets rolled into the standard builds!

I could upload an avrdude executable for Linux, if that would help?

**Comment by davidsainty** [comment]
An example command:

avrdude -c xbee -P 0013a20040acdddd@/dev/ttyUSB0  -p m328p -U "flash:w:test.hex"

**Comment by ghost** [comment]
Good morning. I work for a software company so I will ask some linux guys today if they know how to do the "patch" Ideally if I need a linux type environment I will be using a Pi. (I also have a mac PC if I need to use it too)

I downloaded the zip for avrdude. There are MANY files. which file would you patch? Avrdude.c ?

From what I am reading there may be a way to increase the baud rate to have faster uploads rather than 9600? Do you have a tutorial on that? 

Does uploading a new sketch over OTA keep the EEPROM values? Lets say I store my parameters in the 512 bytes for something, will they retain?

Thanks!!!!!!

**Comment by davidsainty** [comment]
- Files: there is more than one in the patch, including a complete new
  file. Your Linux team should get you going :)
- 9600bps - it can go higher, but maybe start with 9600, it should keep
  things simpler.
- Yes, eeprom is retained. xbeeboot doesn't touch the eeprom at all.

**Comment by ghost** [comment]
Okay, where I am at:
6.1 is patchable. 6.2 gave me problems. 

I used this link to help compile in Raspberry Pi
https://learn.adafruit.com/program-an-avr-or-arduino-using-raspberry-pi-gpio-pins/installation

Now I used your test command just to see if I would get an error:
avrdude -c xbee -P 0013a20040acdddd@/dev/ttyUSB0 -p m328p -U "flash:w:test.hex"

RIght now all I get is a blinking cursor.

**Comment by davidsainty** [comment]
The address 0013a20040acdddd needs to be replaced with the address of your
remote XBee.

The /dev/ttyUSB0 needs to be the serial device connected to your local XBee.

If you are just getting a flashing cursor, I think maybe it's the local bit
that isn't going well.

Try running avrdude with more debugging.  Use several -v options to avrdude
to pump up the output.

**Comment by ghost** [comment]
ser_recv(): programmer is not responding
sendAPIrequest(): bunch of #'s
xbeedev_poll() received frame type 8b

the FTDI is USB0 and I entered the correct MAC.

**Comment by davidsainty** [comment]
Hmm. That last line is very encouraging, it sounds like you are talking to
your local XBee ok.

Are the XBees both configured so they can talk together? Shared encryption
keys etc?

**Comment by ghost** [comment]
Everything is correct. When I try to burn the bootloader again I get this:

 ***failed;  
avrdude: WARNING: invalid value for unused bits in fuse "efuse", should be set to 1 according to datasheet
This behaviour is deprecated and will result in an error in future version
You probably want to use 0xfd instead of 0x05 (double check with your datasheet first).

**Comment by ghost** [comment]
Arduino UNO being programmed over USBTiny

I am choosing, (xBeeBoot) on 32 pin CPU, ATMEGA328P, 16MHZ

**Comment by davidsainty** [comment]
Might have to come back to that.

I think try using more avrdude -v -v -v -v options and see what it tells
us. We should, at a minimum, be able to tell that the two XBees are talking
together. If they aren't talking together successfully, the bootloader
won't be receiving anything either...

**Comment by ghost** [comment]
I see  send and seperate recieve packets. They are communicating. I think it may be a problem with the bootloader of the arduino. I cant seep to send any sketches over USB to it.

**Comment by ghost** [comment]
I verified that when I run the avrdude command, it turns the pin low for a second.

**Comment by ghost** [comment]
I just tried an Atmega 328P nano pro 8Mhz. The bootloader says its fine, I can upload sketches over the programmer but not over serial USB. I get same thing, AT commands go through fine. I exported 2 blink examples, a slow and fast hex and I am trying to push that to the remote xbee for my test.

**Comment by ghost** [comment]
`pi@raspberrypi:~/patch $ avrdude -c xbee -P 0013a20040F7442B@/dev/ttyUSB0 -p m328p -U "flash:w:slow.hex" -v -v -v -v

avrdude: Version 6.1, compiled on Oct 10 2016 at 18:02:40
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

```
     System wide configuration file is "/usr/local/etc/avrdude.conf"
     User configuration file is "/home/pi/.avrduderc"
     User configuration file does not exist or is not a regular file, skipping

     Using Port                    : 0013a20040F7442B@/dev/ttyUSB0
     Using Programmer              : xbee
```

avrdude: XBee address: 0013a20040f7442b
avrdude: Baud 9600
avrdude: Local AT command: AP
avrdude: sendAPIRequest(): 1476133449.572723 -1, 1, -1, 65
avrdude: Send: ~ [7e] . [00] . [05] . [08] . [01] A [41] P [50] . [02] c [63]
avrdude: Recv: ~ [7e]
avrdude: Recv: . [00]
avrdude: Recv: . [05]
avrdude: Recv: . [88]
avrdude: Recv: . [01]
avrdude: Recv: A [41]
avrdude: Recv: P [50]
avrdude: Recv: . [00]
avrdude: Recv: . [e5]
avrdude: xbeedev_poll(): Received frame type 88
avrdude: xbeedev_poll(): Local command AP result code 0
avrdude: Remote AT command: D6
avrdude: sendAPIRequest(): 1476133449.592975 -1, 2, -1, 68
avrdude: Send: ~ [7e] . [00] . [10] . [17] . [02] . [00] } [7d] 3 [33] . [a2] . [00] @ [40] . [f7] D [44] + [2b] . [ff] . [fe] . [02] D [44] 6 [36] . [00] . [12]
avrdude: Recv: ~ [7e]
avrdude: Recv: . [00]
avrdude: Recv: . [0f]
avrdude: Recv: . [97]
avrdude: Recv: . [02]
avrdude: Recv: . [00]
avrdude: Recv: } [7d]
avrdude: Recv: 3 [33]
avrdude: Recv: . [a2]
avrdude: Recv: . [00]
avrdude: Recv: @ [40]
avrdude: Recv: . [f7]
avrdude: Recv: D [44]
avrdude: Recv: + [2b]
avrdude: Recv: | [7c]
avrdude: Recv: B [42]
avrdude: Recv: D [44]
avrdude: Recv: 6 [36]
avrdude: Recv: . [00]
avrdude: Recv: . [d3]
avrdude: xbeedev_poll(): Received frame type 97
avrdude: xbeedev_poll(): Remote command 2 result code 0
avrdude: Remote AT command: D3
avrdude: sendAPIRequest(): 1476133449.704974 -1, 2, -1, 68
avrdude: Send: ~ [7e] . [00] . [10] . [17] . [03] . [00] } [7d] 3 [33] . [a2] . [00] @ [40] . [f7] D [44] + [2b] . [ff] . [fe] . [02] D [44] 3 [33] . [04] . [10]
avrdude: Recv: ~ [7e]
avrdude: Recv: . [00]
avrdude: Recv: . [0f]
avrdude: Recv: . [97]
avrdude: Recv: . [03]
avrdude: Recv: . [00]
avrdude: Recv: } [7d]
avrdude: Recv: 3 [33]
avrdude: Recv: . [a2]
avrdude: Recv: . [00]
avrdude: Recv: @ [40]
avrdude: Recv: . [f7]
avrdude: Recv: D [44]
avrdude: Recv: + [2b]
avrdude: Recv: | [7c]
avrdude: Recv: B [42]
avrdude: Recv: D [44]
avrdude: Recv: 3 [33]
avrdude: Recv: . [00]
avrdude: Recv: . [d5]
avrdude: xbeedev_poll(): Received frame type 97
avrdude: xbeedev_poll(): Remote command 3 result code 0
avrdude: Remote AT command: D3
avrdude: sendAPIRequest(): 1476133450.071238 -1, 2, -1, 68
avrdude: Send: ~ [7e] . [00] . [10] . [17] . [04] . [00] } [7d] 3 [33] . [a2] . [00] @ [40] . [f7] D [44] + [2b] . [ff] . [fe] . [02] D [44] 3 [33] . [05] . [0e]
avrdude: Recv: ~ [7e]
avrdude: Recv: . [00]
avrdude: Recv: . [0f]
avrdude: Recv: . [97]
avrdude: Recv: . [04]
avrdude: Recv: . [00]
avrdude: Recv: } [7d]
avrdude: Recv: 3 [33]
avrdude: Recv: . [a2]
avrdude: Recv: . [00]
avrdude: Recv: @ [40]
avrdude: Recv: . [f7]
avrdude: Recv: D [44]
avrdude: Recv: + [2b]
avrdude: Recv: | [7c]
avrdude: Recv: B [42]
avrdude: Recv: D [44]
avrdude: Recv: 3 [33]
avrdude: Recv: . [00]
avrdude: Recv: . [d4]
avrdude: xbeedev_poll(): Received frame type 97
avrdude: xbeedev_poll(): Remote command 4 result code 0
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1476133451.234942 1, 1, 23, 48
avrdude: Send: ~ [7e] . [00] } [7d] 3 [33] . [10] . [05] . [00] } [7d] 3 [33] . [a2] . [00] @ [40] . [f7] D [44] + [2b] . [ff] . [fe] . [00] . [00] . [01] . [01] . [17] 0 [30]   [20] ) [29]
avrdude: Recv: ~ [7e]
avrdude: Recv: . [00]
avrdude: Recv: . [07]
avrdude: Recv: . [8b]
avrdude: Recv: . [05]
avrdude: Recv: | [7c]
avrdude: Recv: B [42]
avrdude: Recv: . [04]
avrdude: Recv: . [00]
avrdude: Recv: . [00]
avrdude: Recv: . [ad]
avrdude: xbeedev_poll(): Received frame type 8b
avrdude: xbeedev_poll(): Transmit status 5 result code 0
avrdude: ser_recv(): programmer is not responding
avrdude: sendAPIRequest(): 1476133452.338316 1, 1, 23, 48
avrdude: Send: ~ [7e] . [00] } [7d] 3 [33] . [10] . [06] . [00] } [7d] 3 [33] . [a2] . [00] @ [40] . [f7] D [44] + [2b] . [ff] . [fe] . [00] . [00] . [01] . [01] . [17] 0 [30]   [20] ( [28]
avrdude: Recv: ~ [7e]
avrdude: Recv: . [00]
avrdude: Recv: . [07]
avrdude: Recv: . [8b]
avrdude: Recv: . [06]
avrdude: Recv: | [7c]
avrdude: Recv: B [42]
avrdude: Recv: . [00]
avrdude: Recv: . [00]
avrdude: Recv: . [00]
avrdude: Recv: . [b0]`

**Comment by ghost** [comment]
From the sounds of it, I have the same problem that the other thread said he had but I am programming the Atmega chips with Arduino IDE on Windows. What do I need to do to the boards.txt file to make it work correctly?

**Comment by davidsainty** [comment]
It's possible. Try pulling the latest from git, I accepted a related change
earlier today...

**Comment by ghost** [comment]
I checked the changes, rolled them back, same thing. Its strange, when I flash the bootloader (or at least I think it flashed) the LED pin stays high.

**Comment by ghost** [comment]
I flashed standard Opti-boot and that works uploading over serial. I wonder whats broken

**Comment by ghost** [comment]
I just tried the board file on a Mac laptop and same thing, LED high and I dont think it worked properly.

**Comment by davidsainty** [comment]
That's good. As you said, the fuses could be wrong, that might explain it.

The baud rate could be a factor too - normal arduino rate is 19200.

It'll probably be a few hours before I can look at this properly...

**Comment by ghost** [comment]
I just tried to upload the firmware on a Windows PC using avrdude directly. Here was the response:

C:\Users\Stavros\Desktop\xbeeBoot\xbeeboot\bootloaders\xbeeboot>avrdude -c usbtiny -p m328p -b9600 -e -u -U lock:w:0x3f:m -U efuse:w:0x05:m -U hfuse:w:0xDC:m -U lfuse:w:0xFF:m -U flash:w:xbeeboot_atmega328.hex -U lock:w:0x2f:m

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: erasing chip
avrdude: reading input file "0x3f"
avrdude: writing lock (1 bytes):

Writing | ################################################## | 100% 0.00s

avrdude: 1 bytes of lock written
avrdude: verifying lock memory against 0x3f:
avrdude: load data lock data from input file 0x3f:
avrdude: input file 0x3f contains 1 bytes
avrdude: reading on-chip lock data:

Reading | ################################################## | 100% 0.00s

avrdude: verifying ...
avrdude: 1 bytes of lock verified
avrdude: reading input file "0x05"
avrdude: writing efuse (1 bytes):

Writing |                                                    | 0% 0.00s ***failed;
Writing | ################################################## | 100% 0.04s

avrdude: 1 bytes of efuse written
avrdude: verifying efuse memory against 0x05:
avrdude: load data efuse data from input file 0x05:
avrdude: input file 0x05 contains 1 bytes
avrdude: reading on-chip efuse data:

Reading | ################################################## | 100% 0.00s

avrdude: verifying ...
avrdude: verification error, first mismatch at byte 0x0000
         0xfd != 0x05
avrdude: verification error; content mismatch

avrdude done.  Thank you.

**Comment by ghost** [comment]
Here is without adding the fuses but still the LED light is on high

`
C:\Users\Stavros\Desktop\xbeeBoot\xbeeboot\bootloaders\xbeeboot>avrdude -c usbtiny -p m328p -U flash:w:xbeeboot_atmega328.hex

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: reading input file "xbeeboot_atmega328.hex"
avrdude: input file xbeeboot_atmega328.hex auto detected as Intel Hex
avrdude: writing flash (32768 bytes):

Writing | ################################################## | 100% 0.01s

avrdude: 32768 bytes of flash written
avrdude: verifying flash memory against xbeeboot_atmega328.hex:
avrdude: load data flash data from input file xbeeboot_atmega328.hex:
avrdude: input file xbeeboot_atmega328.hex auto detected as Intel Hex
avrdude: input file xbeeboot_atmega328.hex contains 32768 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.02s

avrdude: verifying ...
avrdude: 32768 bytes of flash verified

avrdude: safemode: Fuses OK (E:FD, H:DC, L:FF)

avrdude done.  Thank you.

C:\Users\Stavros\Desktop\xbeeBoot\xbeeboot\bootloaders\xbeeboot>`

**Comment by ghost** [comment]
Okay, I think I did everything I could without you looking into it..  I got the firmware to pass / upload and bypass the miss-match error by changing 0x05 to 0xFD but the led pin is still high. Maybe something wrong somewhere. I am using a 28 pin 328P Arduino Uno for testing. I also have 32 pin arduino pro's all over the place. Here is the verification that the firmware passed:

`
C:\Users\Stavros\Desktop\xbeeBoot\xbeeboot\bootloaders\xbeeboot>avrdude -c usbtiny -p m328p -b9600 -e -u -U lock:w:0x3f:m -U efuse:w:0xFD:m -U hfuse:w:0xDC:m -U lfuse:w:0xFF:m -U flash:w:xbeeboot_atmega328.hex -U lock:w:0x2f:m

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: erasing chip
avrdude: reading input file "0x3f"
avrdude: writing lock (1 bytes):

Writing | ################################################## | 100% 0.00s

avrdude: 1 bytes of lock written
avrdude: verifying lock memory against 0x3f:
avrdude: load data lock data from input file 0x3f:
avrdude: input file 0x3f contains 1 bytes
avrdude: reading on-chip lock data:

Reading | ################################################## | 100% 0.00s

avrdude: verifying ...
avrdude: 1 bytes of lock verified
avrdude: reading input file "0xFD"
avrdude: writing efuse (1 bytes):

Writing | ################################################## | 100% 0.00s

avrdude: 1 bytes of efuse written
avrdude: verifying efuse memory against 0xFD:
avrdude: load data efuse data from input file 0xFD:
avrdude: input file 0xFD contains 1 bytes
avrdude: reading on-chip efuse data:

Reading | ################################################## | 100% 0.00s

avrdude: verifying ...
avrdude: 1 bytes of efuse verified
avrdude: reading input file "0xDC"
avrdude: writing hfuse (1 bytes):

Writing | ################################################## | 100% 0.00s

avrdude: 1 bytes of hfuse written
avrdude: verifying hfuse memory against 0xDC:
avrdude: load data hfuse data from input file 0xDC:
avrdude: input file 0xDC contains 1 bytes
avrdude: reading on-chip hfuse data:

Reading | ################################################## | 100% 0.00s

avrdude: verifying ...
avrdude: 1 bytes of hfuse verified
avrdude: reading input file "0xFF"
avrdude: writing lfuse (1 bytes):

Writing | ################################################## | 100% 0.00s

avrdude: 1 bytes of lfuse written
avrdude: verifying lfuse memory against 0xFF:
avrdude: load data lfuse data from input file 0xFF:
avrdude: input file 0xFF contains 1 bytes
avrdude: reading on-chip lfuse data:

Reading | ################################################## | 100% 0.00s

avrdude: verifying ...
avrdude: 1 bytes of lfuse verified
avrdude: reading input file "xbeeboot_atmega328.hex"
avrdude: input file xbeeboot_atmega328.hex auto detected as Intel Hex
avrdude: writing flash (32768 bytes):

Writing | ################################################## | 100% 0.02s

avrdude: 32768 bytes of flash written
avrdude: verifying flash memory against xbeeboot_atmega328.hex:
avrdude: load data flash data from input file xbeeboot_atmega328.hex:
avrdude: input file xbeeboot_atmega328.hex auto detected as Intel Hex
avrdude: input file xbeeboot_atmega328.hex contains 32768 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.02s

avrdude: verifying ...
avrdude: 32768 bytes of flash verified
avrdude: reading input file "0x2f"
avrdude: writing lock (1 bytes):

Writing | ################################################## | 100% 0.01s

avrdude: 1 bytes of lock written
avrdude: verifying lock memory against 0x2f:
avrdude: load data lock data from input file 0x2f:
avrdude: input file 0x2f contains 1 bytes
avrdude: reading on-chip lock data:

Reading | ################################################## | 100% 0.00s

avrdude: verifying ...
avrdude: 1 bytes of lock verified

avrdude done.  Thank you.

`

**Comment by davidsainty** [comment]
I think those fuses look correct.  You could try 0xfd instead of 0x05
though... I haven't got a datasheet handy but maybe your device isn't
storing the higher bits...

**Comment by ghost** [comment]
I tried 0xfd and that lets me program it, but I still cant communicate over USB

I am going to focus on my 8Mhz 32pin 328P board (Arduino mini pro)

Is there anything I need to do to the IDE to make it talk to the board?

**Comment by davidsainty** [comment]
LED high might be OK. Given that you have got a verified flash with fuses
that look reasonable, see if you can avrdude it directly at 9600 baud?

**Comment by davidsainty** [comment]
I've never actually bothered with the IDE :) xbeeboot does behave like a
normal optiboot though, except at 9600 baud.

Still, for testing it might be easier to avoid the IDE until it responds to
manual testing properly...

**Comment by ghost** [comment]
Here is when I try to program of serial, if I program directly into spi then it works... of course because it doesnt need the bootloader :

C:\Users\Stavros\Desktop\xbeeBoot\xbeeboot\bootloaders\xbeeboot>avrdude -c stk500v1 -p m328p COM12 -b9600 -U flash:w:slow.hex
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x03
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x03
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x03
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x03
^C

**Comment by ghost** [comment]
This is the command I have been using and changing the fuses to see if anything would work:

avrdude -c usbtiny -p m328p -b9600 -e -u -U lock:w:0x3f:m -U efuse:w:0xFD:m -U hfuse:w:0xDC:m -U lfuse:w:0xFF:m -U flash:w:xbeeboot_atmega328.hex -U lock:w:0x2f:m

Here is Opti-boot's board files:

##############################################################

## Optiboot on 28-pin processors (atmega8/88/168/328/etc)

menu.cpu=Processor
menu.mhz=CPU Speed

optiboot28.name=Optiboot on 28-pin cpus

optiboot28.upload.tool=arduino:avrdude
optiboot28.upload.protocol=arduino
optiboot28.upload.speed=115200

optiboot28.bootloader.tool=arduino:avrdude
optiboot28.bootloader.low_fuses=0xF7
optiboot28.bootloader.unlock_bits=0x3F
optiboot28.bootloader.lock_bits=0x2F
optiboot28.build.f_cpu=16000000L

#

# Other Clock speeds.

# For 8MHz using the internal RC Oscillator, we adjust fuses, use the same

# bootloader binary, and halve the upload rate.

#
optiboot28.menu.mhz.16MHz=16MHz
optiboot28.menu.mhz.16MHz.upload.speed=115200
optiboot28.menu.mhz.8MHz=8MHz (int)
optiboot28.menu.mhz.8MHz.build.f_cpu=8000000L
optiboot28.menu.mhz.8MHz.bootloader.low_fuses=0xE2
optiboot28.menu.mhz.8MHz.upload.speed=57600
optiboot28.menu.mhz.1MHz=1MHz (int)
optiboot28.menu.mhz.1MHz.build.f_cpu=1000000L
optiboot28.menu.mhz.1MHz.bootloader.low_fuses=0x62
optiboot28.menu.mhz.1MHz.upload.speed=9600

# optiboot platforms should be UNO-like more than anything else.

optiboot28.build.board=AVR_UNO
optiboot28.build.core=arduino:arduino
optiboot28.build.variant=arduino:standard

## Optiboot for ATmega328p

## ---------------------------------------------

optiboot28.menu.cpu.atmega328p=ATmega328p
optiboot28.menu.cpu.atmega328p.upload.maximum_size=32256
optiboot28.menu.cpu.atmega328p.upload.maximum_data_size=2048

optiboot28.menu.cpu.atmega328p.bootloader.high_fuses=0xDE
optiboot28.menu.cpu.atmega328p.bootloader.extended_fuses=0x05
optiboot28.menu.cpu.atmega328p.bootloader.file=optiboot/optiboot_atmega328.hex

optiboot28.menu.cpu.atmega328p.build.mcu=atmega328p

---

Here is your board file:

##############################################################

## XBeeBoot on 28-pin processors (atmega8/88/168/328/etc)

menu.cpu=Processor
menu.mhz=CPU Speed

xbeeboot28.name=XBeeBoot on 28-pin cpus

xbeeboot28.upload.tool=arduino:avrdude
xbeeboot28.upload.protocol=arduino
xbeeboot28.upload.speed=115200

xbeeboot28.bootloader.tool=arduino:avrdude
xbeeboot28.bootloader.low_fuses=0xF7
xbeeboot28.bootloader.unlock_bits=0x0F
xbeeboot28.bootloader.lock_bits=0x2F
xbeeboot28.build.f_cpu=16000000L

#

# Other Clock speeds.

# For 8MHz using the internal RC Oscillator, we adjust fuses, use the same

# bootloader binary, and halve the upload rate.

#
xbeeboot28.menu.mhz.16MHz=16MHz
xbeeboot28.menu.mhz.16MHz.upload.speed=115200
xbeeboot28.menu.mhz.8MHz=8MHz (int)
xbeeboot28.menu.mhz.8MHz.build.f_cpu=8000000L
xbeeboot28.menu.mhz.8MHz.bootloader.low_fuses=0xE2
xbeeboot28.menu.mhz.8MHz.upload.speed=57600
xbeeboot28.menu.mhz.1MHz=1MHz (int)
xbeeboot28.menu.mhz.1MHz.build.f_cpu=1000000L
xbeeboot28.menu.mhz.1MHz.bootloader.low_fuses=0x62
xbeeboot28.menu.mhz.1MHz.upload.speed=9600

# xbeeboot platforms should be UNO-like more than anything else.

xbeeboot28.build.board=AVR_UNO
xbeeboot28.build.core=arduino:arduino
xbeeboot28.build.variant=arduino:standard

## XBeeBoot for ATmega328p

## ---------------------------------------------

xbeeboot28.menu.cpu.atmega328p=ATmega328p
xbeeboot28.menu.cpu.atmega328p.upload.maximum_size=32256
xbeeboot28.menu.cpu.atmega328p.upload.maximum_data_size=2048

xbeeboot28.menu.cpu.atmega328p.bootloader.low_fuses=0xFF
xbeeboot28.menu.cpu.atmega328p.bootloader.high_fuses=0xDC
xbeeboot28.menu.cpu.atmega328p.bootloader.extended_fuses=0x05
xbeeboot28.menu.cpu.atmega328p.bootloader.file=xbeeboot/xbeeboot_atmega328.hex

xbeeboot28.menu.cpu.atmega328p.build.mcu=atmega328p

**Comment by ghost** [comment]
Though board files dont matter if I am programming it directly...

**Comment by davidsainty** [comment]
The baud rate is sensitive to the crystal MHz - is 19200 any better?

**Comment by ghost** [comment]
Well it works... On the mini pro. 

For reference:
On Windows I flashed the bootloader (easier to setup usbtiny instead of linux)
avrdude -c usbtiny -p m328p -b9600 -e -u -U lock:w:0x3f:m -U efuse:w:0xFD:m -U hfuse:w:0xDC:m -U lfuse:w:0xFF:m -U flash:w:xbeeboot_atmega328_pro_8MHz.hex -U lock:w:0x2f:m

I programmed the file from Raspberry Pi with this command:
avrdude -c xbee -P 0013a20040F7xxxx@/dev/ttyUSB1 -p m328p -U "flash:w:fast.hex" -v -v -v -v

Programming in Arduino IDE does not work right now, will need to figure that out. How can we increase the speed of the upload? By increasing the serial baud rate? thats it? So I dont waste more than 15 hours today, do you know a quick way of doing that? :)

Thanks!!

**Comment by ghost** [comment]
Well this is weird. My sketch is 24KB, I export the compiled binary and now its 68KB... Uh, wtf? lol

**Comment by ghost** [comment]
Hex code takes 3x bigger file size, the actual downloaded size is much less. Phew! Now to figure out increasing the baud rate speed.

**Comment by ghost** [comment]
Can we get this to work for the Arduino Zero, SAMD21 ?

**Comment by davidsainty** [comment]
I think everything about the Arduino Zero is too different to make porting xbeeboot an easy solution.

**Comment by davidsainty** [comment]
In terms of increasing the speed, the xbeeboot bootloader baud rate needs to match the remote XBee's baud rate.  And avrdude's XBee and the avrdude baud rate need to match.  But I suspect that the over-the-air speed is probably the limiting factor, so I've never tried boosting the speed - I stuck with 9600 baud because that's the default XBee speed.
