### ISSUE TITLE
Pin wake xBee

### ISSUE THREAD

**Issue by ghost** [davidsainty/optiboot#6]
If the xBee's are setup so they go to sleep and only wake on pin change, does this effect OTA if the processor is flashed?

**Comment by davidsainty** [comment]
I'm not sure what the implications of that would be, but it can probably be
made to work.

I think your circuit should ensure that a reset Atmel guarantees a
non-sleeping XBee.  That seems like the safest arrangement for reducing the
likelihood of losing contact with the XBee/Atmel.

But the key would be having the XBee wake up at least at some point.  With
pin sleep the XBee could sleep indefinitely.

**Comment by ghost** [comment]
If the MCU is being flashed, are all the DIO pins floating / low? if thats the case, then it should be fine... your thoughts?

**Comment by davidsainty** [comment]
They all float, I believe.  Which is normally interpreted as high, rather
than low.  If you connect a DIO pin directly to the XBee sleep pin it kind
of looks like a MCU reset will force the XBee to sleep.

However, it seems a bit risky that an unconnected pin is interpreted as "go
to sleep" - so you might find it behaves differently in reality.

**Comment by ghost** [comment]
Can we edit the bootloader to have a pin always tied to GND during firmware boot? I just tested, floating pins dont help my issue. If I am in the process of using the bootloader, non of the pins can keep the xBee awake. Or better yet edit the xBee library so that it keeps itself awake using its own DIO pin.

**Comment by davidsainty** [comment]
I see some disadvantage to doing that, because it forces a general purpose pin into a non-standard driving state.  I think perhaps a high value resistor pulling the wake pin low could be a simple solution?  I haven't done the maths, but something like 100k might work ok with very little lost power...

**Comment by davidsainty** [comment]
I think changing the avrdude patch to disable pin sleep would also work.

Of course, either way, if the Atmel never wakes the XBee up, OTA will be impossible.
