### ISSUE TITLE
custom location for OTA

### ISSUE THREAD

**Issue by ghost** [davidsainty/optiboot#8]
Does the bootloader determine where the OTA is coming from. Example, if a Router Module initiates an OTA, does the sensor know where its getting the data from or is it looking for only the coordinator? If its only looking for the coordinator, is there a way to fix that ?

**Comment by davidsainty** [comment]
Any device can initiate, the bootloader responds to the address that
initiated.  It doesn't need to be the coordinator.

Enabling encryption on your XBee network is recommended :)

**Comment by ghost** [comment]
You are the best! Thanks
